repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
    args:
      - "--unsafe"
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      args: ['--count', '--ignore', 'E501, E203, W503']
      exclude: "reference_files"
